### ISSUE TITLE
HOWTO link on FAQ is broken

### ISSUE THREAD

**Issue by eliottwiener** [rsnapshot/rsnapshot.github.io#1]
Link found here: http://rsnapshot.org/faq.html

Link points to here: http://rsnapshot.org/howto/1.2/rsnapshot-HOWTO.en.html#restoring_backups

That file seems to be in the main rsnapshot repo: https://github.com/rsnapshot/rsnapshot/blob/master/docs/HOWTOs/rsnapshot-HOWTO.en.html

**Comment by bebehei** [comment]
rsnapshot/rsnapshot#93 will close this thing. Wednesday next week, I will upload an updated howto.

**Comment by jarofgreen** [comment]
Any progress on this? Also, the HOWTO text on the front page should really be a link to. 

"If this is your first experience with rsnapshot, you may want to read the rsnapshot HOWTO at http://www.rsnapshot.org/. "

Thanks.

**Comment by cpitclaudel** [comment]
Indeed, where is the how to?

**Comment by elacheche** [comment]
Issue won't  be fixed soon?

**Comment by H4kor** [comment]
Still an issue
